#!/usr/bin/env bash
# alr - assembly, link & run!

if [ $# -ne 1 ]; then
    echo "only one argument can be specified"
    exit
elif ! test -f "$1.S"; then
    echo "$1.S does not exist"
    exit
fi

AFLAGS="-felf64"
LFLAGS="-lc"

if test -f /lib/ld-linux-x86-64.so.2; then
	LFLAGS="$LFLAGS --dynamic-linker /lib/ld-linux-x86-64.so.2"
elif test -f /lib64/ld-linux-x86-64.so.2; then
	LFLAGS="$LFLAGS --dynamic-linker /lib64/ld-linux-x86-64.so.2"
fi

nasm $AFLAGS $1.S -o $1.o && \
 ld  $LFLAGS $1.o -o $1   && \
./$1
